webserver:
  hosts:
    ubu1:
      ansible_ssh_user: vagrant
      ansible_ssh_host: 127.0.0.1
      ansible_ssh_port: 2721
      ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.vagrant.d/insecure_private_key"

database:
  hosts:
    ubu2:
      ansible_ssh_user: vagrant
      ansible_ssh_host: 127.0.0.1
      ansible_ssh_port: 2722
      ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.vagrant.d/insecure_private_key"
