webserver:
  hosts:
    ubu1:
      ansible_ssh_user: vmuser
      ansible_ssh_host: webserver.mhost.net
      ansible_ssh_port: 22
      ansible_ssh_private_key_file: ssh_key/multipass-ssh-key

database:
  hosts:
    ubu2:
      ansible_ssh_user: vmuser
      ansible_ssh_host: database.mhost.net
      ansible_ssh_port: 22
      ansible_ssh_private_key_file: ssh_key/multipass-ssh-key
