name: Validate Exercices
on: [push, pull_request, workflow_call, workflow_dispatch]

jobs:

  setup:
    steps:
      - uses: actions/checkout@v2

      - name: Install multipass
        run: snap install multipass --classic
